name: upload-changed-workflows-to-khronograph.yml

on:
  push:
    paths:
      - '*.json'
    branches: [ main ]

jobs:
  list-workflows:
    runs-on: ubuntu-latest
    outputs:
      matrix-added: ${{ steps.file-changes.outputs.files_added }}
      matrix-modified: ${{ steps.file-changes.outputs.files_modified }}
    steps:
      - id: file-changes
        uses: trilom/file-changes-action@v1.2.4
  upload-workflows-added:
    needs: list-workflows
    runs-on: ubuntu-latest
    strategy:
        matrix:
            workflow: ${{ fromJSON(needs.list-workflows.outputs.matrix-added) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
        
      - name: Echo file
        run: |
          echo ${{ matrix.workflow }} # to test if the correct file was passed
          
      - name: Upload workflows
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://www.google.com/'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          file: "${{ github.workspace }}/${{ matrix.workflow }}"
  upload-workflows-modified:
    needs: list-workflows
    runs-on: ubuntu-latest
    strategy:
        matrix:
            workflow: ${{ fromJSON(needs.list-workflows.outputs.matrix-modified) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
        
      - name: Echo file
        run: |
          echo ${{ matrix.workflow }} # to test if the correct file was passed
          
      - name: Upload workflows
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://www.google.com/'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          file: "${{ github.workspace }}/${{ matrix.workflow }}"
